// <auto-generated />
using System;
using App.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.DAL.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507162105_REMOVED_ALTERNATE_KEYS_REPLACE_WITH_UNIQUE_INDEX")]
    partial class REMOVED_ALTERNATE_KEYS_REPLACE_WITH_UNIQUE_INDEX
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagementCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId")
                        .HasDatabaseName("ix_contact_contact_type_id_fk");

                    b.HasIndex("ManagementCompanyId")
                        .HasDatabaseName("ix_contact_mcompany_id_fk");

                    b.HasIndex("ManagementCompanyId", "ContactTypeId", "ContactValue")
                        .IsUnique()
                        .HasDatabaseName("ux_contact_company_type_value");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("App.Domain.ContactType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_contact_type_code");

                    b.ToTable("ContactTypes");
                });

            modelBuilder.Entity("App.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagementCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RegistryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ManagementCompanyId")
                        .HasDatabaseName("ix_customer_by_company");

                    b.HasIndex("ManagementCompanyId", "RegistryCode")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_company_registry_code");

                    b.HasIndex("ManagementCompanyId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_company_slug");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("App.Domain.CustomerRepresentative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerRepresentativeRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_representative_customer_id_fk");

                    b.HasIndex("CustomerRepresentativeRoleId")
                        .HasDatabaseName("ix_customer_representative_role_id_fk");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_customer_representative_resident_id_fk");

                    b.ToTable("CustomerRepresentatives");
                });

            modelBuilder.Entity("App.Domain.CustomerRepresentativeRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_representative_role_code");

                    b.ToTable("CustomerRepresentativeRoles");
                });

            modelBuilder.Entity("App.Domain.Identity.AppRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PreviousExpirationDT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousRefreshToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("App.Domain.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("App.Domain.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("App.Domain.Lease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeaseRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaseRoleId")
                        .HasDatabaseName("ix_lease_lease_role_id_fk");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_lease_resident_id_fk");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_lease_unit_id_fk");

                    b.HasIndex("ResidentId", "UnitId", "StartDate")
                        .HasDatabaseName("ix_lease_resident_unit_start_date");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("App.Domain.LeaseRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("LeaseRoles");
                });

            modelBuilder.Entity("App.Domain.ManagementCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RegistryCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RegistryCode")
                        .IsUnique()
                        .HasDatabaseName("ux_management_company_registry_code");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_management_company_slug");

                    b.ToTable("ManagementCompanies");
                });

            modelBuilder.Entity("App.Domain.ManagementCompanyJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagementCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagementCompanyJoinRequestStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RequestedManagementCompanyRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByAppUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_mcompany_join_request_appuser_id_fk");

                    b.HasIndex("ManagementCompanyId")
                        .HasDatabaseName("ix_mcompany_join_request_mcompany_id_fk");

                    b.HasIndex("ManagementCompanyJoinRequestStatusId")
                        .HasDatabaseName("ix_mcompany_join_request_status_id_fk");

                    b.HasIndex("RequestedManagementCompanyRoleId")
                        .HasDatabaseName("ix_mcompany_join_request_requested_role_id_fk");

                    b.HasIndex("ResolvedByAppUserId")
                        .HasDatabaseName("ix_mcompany_join_request_resolved_by_appuser_id_fk");

                    b.HasIndex("AppUserId", "ManagementCompanyId")
                        .IsUnique()
                        .HasDatabaseName("ux_mcompany_join_request_pending_user_company")
                        .HasFilter("\"ManagementCompanyJoinRequestStatusId\" = '11111111-1111-1111-1111-111111111111'");

                    b.HasIndex("ManagementCompanyId", "ManagementCompanyJoinRequestStatusId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_mcompany_join_request_company_status_created_at");

                    b.ToTable("ManagementCompanyJoinRequests");
                });

            modelBuilder.Entity("App.Domain.ManagementCompanyJoinRequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_mcompany_join_request_status_code");

                    b.ToTable("ManagementCompanyJoinRequestStatuses");
                });

            modelBuilder.Entity("App.Domain.ManagementCompanyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_mcompany_role_code");

                    b.ToTable("ManagementCompanyRoles");
                });

            modelBuilder.Entity("App.Domain.ManagementCompanyUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ManagementCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagementCompanyRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_mcompany_user_appuser_id_fk");

                    b.HasIndex("ManagementCompanyId")
                        .HasDatabaseName("ix_mcompany_user_mcompany_id_fk");

                    b.HasIndex("ManagementCompanyRoleId")
                        .HasDatabaseName("ix_mcompany_user_mcompany_role_id_fk");

                    b.HasIndex("ManagementCompanyId", "AppUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_mcompany_user_pair");

                    b.ToTable("ManagementCompanyUsers");
                });

            modelBuilder.Entity("App.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PropertyTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_property_customer_id_fk");

                    b.HasIndex("PropertyTypeId")
                        .HasDatabaseName("ix_property_property_type_id_fk");

                    b.HasIndex("CustomerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_property_customer_slug");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("App.Domain.PropertyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_property_type_code");

                    b.ToTable("PropertyTypes");
                });

            modelBuilder.Entity("App.Domain.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ManagementCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ManagementCompanyId")
                        .HasDatabaseName("ix_resident_by_company");

                    b.HasIndex("ManagementCompanyId", "IdCode")
                        .IsUnique()
                        .HasDatabaseName("ux_resident_company_id_code");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("App.Domain.ResidentContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_resident_contact_contact_id_fk");

                    b.HasIndex("ResidentId")
                        .IsUnique()
                        .HasDatabaseName("ux_resident_contact_one_primary")
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.ToTable("ResidentContacts");
                });

            modelBuilder.Entity("App.Domain.ResidentUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_resident_user_appuser_id_fk");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_resident_user_resident_id_fk");

                    b.HasIndex("ResidentId", "AppUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_resident_user_pair");

                    b.ToTable("ResidentUsers");
                });

            modelBuilder.Entity("App.Domain.ScheduledWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("RealEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RealStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_scheduled_work_ticket_id_fk");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_scheduled_work_vendor_id_fk");

                    b.HasIndex("WorkStatusId")
                        .HasDatabaseName("ix_scheduled_work_work_status_id_fk");

                    b.HasIndex("VendorId", "ScheduledStart")
                        .HasDatabaseName("ix_scheduled_work_vendor_scheduled_start");

                    b.ToTable("ScheduledWorks");
                });

            modelBuilder.Entity("App.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagementCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TicketNr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TicketPriorityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_ticket_customer_id_fk");

                    b.HasIndex("ManagementCompanyId")
                        .HasDatabaseName("ix_ticket_mcompany_id_fk");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_ticket_property_id_fk");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_ticket_resident_id_fk");

                    b.HasIndex("TicketCategoryId")
                        .HasDatabaseName("ix_ticket_ticket_category_id_fk");

                    b.HasIndex("TicketPriorityId")
                        .HasDatabaseName("ix_ticket_ticket_priority_id_fk");

                    b.HasIndex("TicketStatusId")
                        .HasDatabaseName("ix_ticket_ticket_status_id_fk");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_ticket_unit_id_fk");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_ticket_vendor_id_fk");

                    b.HasIndex("ManagementCompanyId", "TicketNr")
                        .IsUnique()
                        .HasDatabaseName("ux_ticket_company_ticket_nr");

                    b.HasIndex("ManagementCompanyId", "TicketStatusId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_ticket_company_status_created_at");

                    b.HasIndex("VendorId", "TicketStatusId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_ticket_vendor_status_created_at");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("App.Domain.TicketCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_ticket_category_code");

                    b.ToTable("TicketCategories");
                });

            modelBuilder.Entity("App.Domain.TicketPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("TicketPriorities");
                });

            modelBuilder.Entity("App.Domain.TicketStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("TicketStatuses");
                });

            modelBuilder.Entity("App.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FloorNr")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SizeM2")
                        .HasColumnType("numeric");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UnitNr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_unit_property_id_fk");

                    b.HasIndex("PropertyId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_unit_property_slug");

                    b.HasIndex("PropertyId", "UnitNr")
                        .IsUnique()
                        .HasDatabaseName("ux_unit_property_unit_nr");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("App.Domain.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagementCompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RegistryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ManagementCompanyId")
                        .HasDatabaseName("ix_vendor_by_company");

                    b.HasIndex("ManagementCompanyId", "RegistryCode")
                        .IsUnique()
                        .HasDatabaseName("ux_vendor_company_registry_code");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("App.Domain.VendorContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleTitle")
                        .HasMaxLength(200)
                        .HasColumnType("jsonb");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_vendor_contact_contact_id_fk");

                    b.HasIndex("VendorId")
                        .IsUnique()
                        .HasDatabaseName("ux_vendor_contact_one_primary")
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.ToTable("VendorContacts");
                });

            modelBuilder.Entity("App.Domain.VendorTicketCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TicketCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketCategoryId")
                        .HasDatabaseName("ix_vtc_category_id_fk");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_vtc_vendor_id_fk");

                    b.HasIndex("VendorId", "TicketCategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_vtc_pair");

                    b.ToTable("VendorTicketCategories");
                });

            modelBuilder.Entity("App.Domain.WorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LaborCost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaterialCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ScheduledWorkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("WorkEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WorkStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("ix_work_log_appuser_id_fk");

                    b.HasIndex("ScheduledWorkId")
                        .HasDatabaseName("ix_work_log_scheduled_work_id_fk");

                    b.HasIndex("ScheduledWorkId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_work_log_schedwork_created_at");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("App.Domain.WorkStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_work_status_code");

                    b.ToTable("WorkStatuses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("App.Domain.Contact", b =>
                {
                    b.HasOne("App.Domain.ContactType", "ContactType")
                        .WithMany("Contacts")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_type");

                    b.HasOne("App.Domain.ManagementCompany", "ManagementCompany")
                        .WithMany("Contacts")
                        .HasForeignKey("ManagementCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_mcompany");

                    b.Navigation("ContactType");

                    b.Navigation("ManagementCompany");
                });

            modelBuilder.Entity("App.Domain.Customer", b =>
                {
                    b.HasOne("App.Domain.ManagementCompany", "ManagementCompany")
                        .WithMany("Customers")
                        .HasForeignKey("ManagementCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_mcompany");

                    b.Navigation("ManagementCompany");
                });

            modelBuilder.Entity("App.Domain.CustomerRepresentative", b =>
                {
                    b.HasOne("App.Domain.Customer", "Customer")
                        .WithMany("CustomerRepresentatives")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_custrep_customer");

                    b.HasOne("App.Domain.CustomerRepresentativeRole", "CustomerRepresentativeRole")
                        .WithMany("CustomerRepresentatives")
                        .HasForeignKey("CustomerRepresentativeRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_custrep_role");

                    b.HasOne("App.Domain.Resident", "Resident")
                        .WithMany("CustomerRepresentatives")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_custrep_resident");

                    b.Navigation("Customer");

                    b.Navigation("CustomerRepresentativeRole");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("App.Domain.Identity.AppRefreshToken", b =>
                {
                    b.HasOne("App.Domain.Identity.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("App.Domain.Lease", b =>
                {
                    b.HasOne("App.Domain.LeaseRole", "LeaseRole")
                        .WithMany("Leases")
                        .HasForeignKey("LeaseRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lease_role");

                    b.HasOne("App.Domain.Resident", "Resident")
                        .WithMany("Leases")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lease_resident");

                    b.HasOne("App.Domain.Unit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lease_unit");

                    b.Navigation("LeaseRole");

                    b.Navigation("Resident");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("App.Domain.ManagementCompanyJoinRequest", b =>
                {
                    b.HasOne("App.Domain.Identity.AppUser", "AppUser")
                        .WithMany("ManagementCompanyJoinRequests")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mcompany_join_request_appuser");

                    b.HasOne("App.Domain.ManagementCompany", "ManagementCompany")
                        .WithMany("JoinRequests")
                        .HasForeignKey("ManagementCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mcompany_join_request_mcompany");

                    b.HasOne("App.Domain.ManagementCompanyJoinRequestStatus", "ManagementCompanyJoinRequestStatus")
                        .WithMany("ManagementCompanyJoinRequests")
                        .HasForeignKey("ManagementCompanyJoinRequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mcompany_join_request_status");

                    b.HasOne("App.Domain.ManagementCompanyRole", "RequestedManagementCompanyRole")
                        .WithMany("ManagementCompanyJoinRequests")
                        .HasForeignKey("RequestedManagementCompanyRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mcompany_join_request_requested_role");

                    b.HasOne("App.Domain.Identity.AppUser", "ResolvedByAppUser")
                        .WithMany("ResolvedManagementCompanyJoinRequests")
                        .HasForeignKey("ResolvedByAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_mcompany_join_request_resolver_appuser");

                    b.Navigation("AppUser");

                    b.Navigation("ManagementCompany");

                    b.Navigation("ManagementCompanyJoinRequestStatus");

                    b.Navigation("RequestedManagementCompanyRole");

                    b.Navigation("ResolvedByAppUser");
                });

            modelBuilder.Entity("App.Domain.ManagementCompanyUser", b =>
                {
                    b.HasOne("App.Domain.Identity.AppUser", "AppUser")
                        .WithMany("ManagementCompanyUsers")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mcompany_user_appuser");

                    b.HasOne("App.Domain.ManagementCompany", "ManagementCompany")
                        .WithMany("ManagementCompanyUsers")
                        .HasForeignKey("ManagementCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mcompany_user_mcompany");

                    b.HasOne("App.Domain.ManagementCompanyRole", "ManagementCompanyRole")
                        .WithMany("ManagementCompanyUsers")
                        .HasForeignKey("ManagementCompanyRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mcompany_user_role");

                    b.Navigation("AppUser");

                    b.Navigation("ManagementCompany");

                    b.Navigation("ManagementCompanyRole");
                });

            modelBuilder.Entity("App.Domain.Property", b =>
                {
                    b.HasOne("App.Domain.Customer", "Customer")
                        .WithMany("Properties")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_property_customer");

                    b.HasOne("App.Domain.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_property_type");

                    b.Navigation("Customer");

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("App.Domain.Resident", b =>
                {
                    b.HasOne("App.Domain.ManagementCompany", "ManagementCompany")
                        .WithMany("Residents")
                        .HasForeignKey("ManagementCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_mcompany");

                    b.Navigation("ManagementCompany");
                });

            modelBuilder.Entity("App.Domain.ResidentContact", b =>
                {
                    b.HasOne("App.Domain.Contact", "Contact")
                        .WithMany("ResidentContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_contact_contact");

                    b.HasOne("App.Domain.Resident", "Resident")
                        .WithMany("ResidentContacts")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_contact_resident");

                    b.Navigation("Contact");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("App.Domain.ResidentUser", b =>
                {
                    b.HasOne("App.Domain.Identity.AppUser", "AppUser")
                        .WithMany("ResidentUsers")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_user_appuser");

                    b.HasOne("App.Domain.Resident", "Resident")
                        .WithMany("ResidentUsers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_user_resident");

                    b.Navigation("AppUser");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("App.Domain.ScheduledWork", b =>
                {
                    b.HasOne("App.Domain.Ticket", "Ticket")
                        .WithMany("ScheduledWorks")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedwork_ticket");

                    b.HasOne("App.Domain.Vendor", "Vendor")
                        .WithMany("ScheduledWorks")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedwork_vendor");

                    b.HasOne("App.Domain.WorkStatus", "WorkStatus")
                        .WithMany("ScheduledWorks")
                        .HasForeignKey("WorkStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedwork_status");

                    b.Navigation("Ticket");

                    b.Navigation("Vendor");

                    b.Navigation("WorkStatus");
                });

            modelBuilder.Entity("App.Domain.Ticket", b =>
                {
                    b.HasOne("App.Domain.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_customer");

                    b.HasOne("App.Domain.ManagementCompany", "ManagementCompany")
                        .WithMany("Tickets")
                        .HasForeignKey("ManagementCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_mcompany");

                    b.HasOne("App.Domain.Property", "Property")
                        .WithMany("Tickets")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_property");

                    b.HasOne("App.Domain.Resident", "Resident")
                        .WithMany("Tickets")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_resident");

                    b.HasOne("App.Domain.TicketCategory", "TicketCategory")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_category");

                    b.HasOne("App.Domain.TicketPriority", "TicketPriority")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketPriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_priority");

                    b.HasOne("App.Domain.TicketStatus", "TicketStatus")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status");

                    b.HasOne("App.Domain.Unit", "Unit")
                        .WithMany("Tickets")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_unit");

                    b.HasOne("App.Domain.Vendor", "Vendor")
                        .WithMany("Tickets")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_vendor");

                    b.Navigation("Customer");

                    b.Navigation("ManagementCompany");

                    b.Navigation("Property");

                    b.Navigation("Resident");

                    b.Navigation("TicketCategory");

                    b.Navigation("TicketPriority");

                    b.Navigation("TicketStatus");

                    b.Navigation("Unit");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("App.Domain.Unit", b =>
                {
                    b.HasOne("App.Domain.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_unit_property");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("App.Domain.Vendor", b =>
                {
                    b.HasOne("App.Domain.ManagementCompany", "ManagementCompany")
                        .WithMany("Vendors")
                        .HasForeignKey("ManagementCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_mcompany");

                    b.Navigation("ManagementCompany");
                });

            modelBuilder.Entity("App.Domain.VendorContact", b =>
                {
                    b.HasOne("App.Domain.Contact", "Contact")
                        .WithMany("VendorContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_contact_contact");

                    b.HasOne("App.Domain.Vendor", "Vendor")
                        .WithMany("VendorContacts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_contact_vendor");

                    b.Navigation("Contact");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("App.Domain.VendorTicketCategory", b =>
                {
                    b.HasOne("App.Domain.TicketCategory", "TicketCategory")
                        .WithMany("VendorTicketCategories")
                        .HasForeignKey("TicketCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vtc_category");

                    b.HasOne("App.Domain.Vendor", "Vendor")
                        .WithMany("VendorTicketCategories")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vtc_vendor");

                    b.Navigation("TicketCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("App.Domain.WorkLog", b =>
                {
                    b.HasOne("App.Domain.Identity.AppUser", "AppUser")
                        .WithMany("WorkLogs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_worklog_appuser");

                    b.HasOne("App.Domain.ScheduledWork", "ScheduledWork")
                        .WithMany("WorkLogs")
                        .HasForeignKey("ScheduledWorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_worklog_schedwork");

                    b.Navigation("AppUser");

                    b.Navigation("ScheduledWork");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Contact", b =>
                {
                    b.Navigation("ResidentContacts");

                    b.Navigation("VendorContacts");
                });

            modelBuilder.Entity("App.Domain.ContactType", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("App.Domain.Customer", b =>
                {
                    b.Navigation("CustomerRepresentatives");

                    b.Navigation("Properties");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("App.Domain.CustomerRepresentativeRole", b =>
                {
                    b.Navigation("CustomerRepresentatives");
                });

            modelBuilder.Entity("App.Domain.Identity.AppUser", b =>
                {
                    b.Navigation("ManagementCompanyJoinRequests");

                    b.Navigation("ManagementCompanyUsers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ResidentUsers");

                    b.Navigation("ResolvedManagementCompanyJoinRequests");

                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("App.Domain.LeaseRole", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("App.Domain.ManagementCompany", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Customers");

                    b.Navigation("JoinRequests");

                    b.Navigation("ManagementCompanyUsers");

                    b.Navigation("Residents");

                    b.Navigation("Tickets");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("App.Domain.ManagementCompanyJoinRequestStatus", b =>
                {
                    b.Navigation("ManagementCompanyJoinRequests");
                });

            modelBuilder.Entity("App.Domain.ManagementCompanyRole", b =>
                {
                    b.Navigation("ManagementCompanyJoinRequests");

                    b.Navigation("ManagementCompanyUsers");
                });

            modelBuilder.Entity("App.Domain.Property", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("App.Domain.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("App.Domain.Resident", b =>
                {
                    b.Navigation("CustomerRepresentatives");

                    b.Navigation("Leases");

                    b.Navigation("ResidentContacts");

                    b.Navigation("ResidentUsers");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("App.Domain.ScheduledWork", b =>
                {
                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("App.Domain.Ticket", b =>
                {
                    b.Navigation("ScheduledWorks");
                });

            modelBuilder.Entity("App.Domain.TicketCategory", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("VendorTicketCategories");
                });

            modelBuilder.Entity("App.Domain.TicketPriority", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("App.Domain.TicketStatus", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("App.Domain.Unit", b =>
                {
                    b.Navigation("Leases");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("App.Domain.Vendor", b =>
                {
                    b.Navigation("ScheduledWorks");

                    b.Navigation("Tickets");

                    b.Navigation("VendorContacts");

                    b.Navigation("VendorTicketCategories");
                });

            modelBuilder.Entity("App.Domain.WorkStatus", b =>
                {
                    b.Navigation("ScheduledWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
