
services:
  aspnet:
    build: .
    container_name: apartmentcrmsaasonion
    ports:
      - "8083:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-dev;Port=5432;Database=apartmentcrmsaasonion;Username=postgres;Password=postgres
    networks:
      - backend

networks:
  backend:
    external: true
    name: backend
