//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminScaffoldText {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal AdminScaffoldText() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Views.AdminScaffoldText", typeof(AdminScaffoldText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string BackToList {
            get { return ResourceManager.GetString(nameof(BackToList), resourceCulture)!; }
        }

        public static string ConfirmDelete {
            get { return ResourceManager.GetString(nameof(ConfirmDelete), resourceCulture)!; }
        }

        public static string Create {
            get { return ResourceManager.GetString(nameof(Create), resourceCulture)!; }
        }

        public static string CreateNew {
            get { return ResourceManager.GetString(nameof(CreateNew), resourceCulture)!; }
        }

        public static string Delete {
            get { return ResourceManager.GetString(nameof(Delete), resourceCulture)!; }
        }

        public static string Details {
            get { return ResourceManager.GetString(nameof(Details), resourceCulture)!; }
        }

        public static string Edit {
            get { return ResourceManager.GetString(nameof(Edit), resourceCulture)!; }
        }

        public static string Index {
            get { return ResourceManager.GetString(nameof(Index), resourceCulture)!; }
        }

    }
}


