//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminText {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal AdminText() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Views.AdminText", typeof(AdminText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Actions { get { return ResourceManager.GetString(nameof(Actions), resourceCulture)!; } }
        public static string Actual { get { return ResourceManager.GetString(nameof(Actual), resourceCulture)!; } }
        public static string Administration { get { return ResourceManager.GetString(nameof(Administration), resourceCulture)!; } }
        public static string AdminDashboard { get { return ResourceManager.GetString(nameof(AdminDashboard), resourceCulture)!; } }
        public static string Address { get { return ResourceManager.GetString(nameof(Address), resourceCulture)!; } }
        public static string Back { get { return ResourceManager.GetString(nameof(Back), resourceCulture)!; } }
        public static string BackToCompanies { get { return ResourceManager.GetString(nameof(BackToCompanies), resourceCulture)!; } }
        public static string BackToTickets { get { return ResourceManager.GetString(nameof(BackToTickets), resourceCulture)!; } }
        public static string BackToUsers { get { return ResourceManager.GetString(nameof(BackToUsers), resourceCulture)!; } }
        public static string Cancel { get { return ResourceManager.GetString(nameof(Cancel), resourceCulture)!; } }
        public static string Category { get { return ResourceManager.GetString(nameof(Category), resourceCulture)!; } }
        public static string Closed { get { return ResourceManager.GetString(nameof(Closed), resourceCulture)!; } }
        public static string Code { get { return ResourceManager.GetString(nameof(Code), resourceCulture)!; } }
        public static string Companies { get { return ResourceManager.GetString(nameof(Companies), resourceCulture)!; } }
        public static string Company { get { return ResourceManager.GetString(nameof(Company), resourceCulture)!; } }
        public static string CompanyMemberships { get { return ResourceManager.GetString(nameof(CompanyMemberships), resourceCulture)!; } }
        public static string CompanyProfile { get { return ResourceManager.GetString(nameof(CompanyProfile), resourceCulture)!; } }
        public static string CompanyUpdatedSuccessfully { get { return ResourceManager.GetString(nameof(CompanyUpdatedSuccessfully), resourceCulture)!; } }
        public static string Context { get { return ResourceManager.GetString(nameof(Context), resourceCulture)!; } }
        public static string Cost { get { return ResourceManager.GetString(nameof(Cost), resourceCulture)!; } }
        public static string Create { get { return ResourceManager.GetString(nameof(Create), resourceCulture)!; } }
        public static string CreateLookup { get { return ResourceManager.GetString(nameof(CreateLookup), resourceCulture)!; } }
        public static string Created { get { return ResourceManager.GetString(nameof(Created), resourceCulture)!; } }
        public static string CreatedFrom { get { return ResourceManager.GetString(nameof(CreatedFrom), resourceCulture)!; } }
        public static string CreatedTo { get { return ResourceManager.GetString(nameof(CreatedTo), resourceCulture)!; } }
        public static string Customer { get { return ResourceManager.GetString(nameof(Customer), resourceCulture)!; } }
        public static string Customers { get { return ResourceManager.GetString(nameof(Customers), resourceCulture)!; } }
        public static string Dashboard { get { return ResourceManager.GetString(nameof(Dashboard), resourceCulture)!; } }
        public static string Delete { get { return ResourceManager.GetString(nameof(Delete), resourceCulture)!; } }
        public static string DeleteLookup { get { return ResourceManager.GetString(nameof(DeleteLookup), resourceCulture)!; } }
        public static string DeleteLookupItem { get { return ResourceManager.GetString(nameof(DeleteLookupItem), resourceCulture)!; } }
        public static string Details { get { return ResourceManager.GetString(nameof(Details), resourceCulture)!; } }
        public static string Due { get { return ResourceManager.GetString(nameof(Due), resourceCulture)!; } }
        public static string DueFrom { get { return ResourceManager.GetString(nameof(DueFrom), resourceCulture)!; } }
        public static string DueTo { get { return ResourceManager.GetString(nameof(DueTo), resourceCulture)!; } }
        public static string Edit { get { return ResourceManager.GetString(nameof(Edit), resourceCulture)!; } }
        public static string EditCompany { get { return ResourceManager.GetString(nameof(EditCompany), resourceCulture)!; } }
        public static string EditLookup { get { return ResourceManager.GetString(nameof(EditLookup), resourceCulture)!; } }
        public static string Email { get { return ResourceManager.GetString(nameof(Email), resourceCulture)!; } }
        public static string FullName { get { return ResourceManager.GetString(nameof(FullName), resourceCulture)!; } }
        public static string HasSystemAdminRole { get { return ResourceManager.GetString(nameof(HasSystemAdminRole), resourceCulture)!; } }
        public static string Hours { get { return ResourceManager.GetString(nameof(Hours), resourceCulture)!; } }
        public static string Label { get { return ResourceManager.GetString(nameof(Label), resourceCulture)!; } }
        public static string Language { get { return ResourceManager.GetString(nameof(Language), resourceCulture)!; } }
        public static string LastLogin { get { return ResourceManager.GetString(nameof(LastLogin), resourceCulture)!; } }
        public static string Lifecycle { get { return ResourceManager.GetString(nameof(Lifecycle), resourceCulture)!; } }
        public static string Locked { get { return ResourceManager.GetString(nameof(Locked), resourceCulture)!; } }
        public static string LockedOnly { get { return ResourceManager.GetString(nameof(LockedOnly), resourceCulture)!; } }
        public static string LockedUsers { get { return ResourceManager.GetString(nameof(LockedUsers), resourceCulture)!; } }
        public static string LockUser { get { return ResourceManager.GetString(nameof(LockUser), resourceCulture)!; } }
        public static string LoggedBy { get { return ResourceManager.GetString(nameof(LoggedBy), resourceCulture)!; } }
        public static string Logout { get { return ResourceManager.GetString(nameof(Logout), resourceCulture)!; } }
        public static string LookupItemCreatedSuccessfully { get { return ResourceManager.GetString(nameof(LookupItemCreatedSuccessfully), resourceCulture)!; } }
        public static string LookupItemDeletedSuccessfully { get { return ResourceManager.GetString(nameof(LookupItemDeletedSuccessfully), resourceCulture)!; } }
        public static string LookupItemUpdatedSuccessfully { get { return ResourceManager.GetString(nameof(LookupItemUpdatedSuccessfully), resourceCulture)!; } }
        public static string Lookups { get { return ResourceManager.GetString(nameof(Lookups), resourceCulture)!; } }
        public static string Name { get { return ResourceManager.GetString(nameof(Name), resourceCulture)!; } }
        public static string No { get { return ResourceManager.GetString(nameof(No), resourceCulture)!; } }
        public static string NoCompaniesFound { get { return ResourceManager.GetString(nameof(NoCompaniesFound), resourceCulture)!; } }
        public static string NoCompanyMemberships { get { return ResourceManager.GetString(nameof(NoCompanyMemberships), resourceCulture)!; } }
        public static string NoLookupItemsConfigured { get { return ResourceManager.GetString(nameof(NoLookupItemsConfigured), resourceCulture)!; } }
        public static string NoRolesAssigned { get { return ResourceManager.GetString(nameof(NoRolesAssigned), resourceCulture)!; } }
        public static string NoScheduledWork { get { return ResourceManager.GetString(nameof(NoScheduledWork), resourceCulture)!; } }
        public static string NoTicketsMatchFilters { get { return ResourceManager.GetString(nameof(NoTicketsMatchFilters), resourceCulture)!; } }
        public static string NoUsersFound { get { return ResourceManager.GetString(nameof(NoUsersFound), resourceCulture)!; } }
        public static string NoWorkLogs { get { return ResourceManager.GetString(nameof(NoWorkLogs), resourceCulture)!; } }
        public static string OpenOnly { get { return ResourceManager.GetString(nameof(OpenOnly), resourceCulture)!; } }
        public static string OpenTickets { get { return ResourceManager.GetString(nameof(OpenTickets), resourceCulture)!; } }
        public static string Overdue { get { return ResourceManager.GetString(nameof(Overdue), resourceCulture)!; } }
        public static string OverdueOnly { get { return ResourceManager.GetString(nameof(OverdueOnly), resourceCulture)!; } }
        public static string OverdueTickets { get { return ResourceManager.GetString(nameof(OverdueTickets), resourceCulture)!; } }
        public static string PendingRequests { get { return ResourceManager.GetString(nameof(PendingRequests), resourceCulture)!; } }
        public static string Phone { get { return ResourceManager.GetString(nameof(Phone), resourceCulture)!; } }
        public static string PlatformAdmin { get { return ResourceManager.GetString(nameof(PlatformAdmin), resourceCulture)!; } }
        public static string Priority { get { return ResourceManager.GetString(nameof(Priority), resourceCulture)!; } }
        public static string Profile { get { return ResourceManager.GetString(nameof(Profile), resourceCulture)!; } }
        public static string Properties { get { return ResourceManager.GetString(nameof(Properties), resourceCulture)!; } }
        public static string Property { get { return ResourceManager.GetString(nameof(Property), resourceCulture)!; } }
        public static string Protected { get { return ResourceManager.GetString(nameof(Protected), resourceCulture)!; } }
        public static string RecentCompanies { get { return ResourceManager.GetString(nameof(RecentCompanies), resourceCulture)!; } }
        public static string RecentUsers { get { return ResourceManager.GetString(nameof(RecentUsers), resourceCulture)!; } }
        public static string RefreshTokens { get { return ResourceManager.GetString(nameof(RefreshTokens), resourceCulture)!; } }
        public static string Registry { get { return ResourceManager.GetString(nameof(Registry), resourceCulture)!; } }
        public static string RegistryCode { get { return ResourceManager.GetString(nameof(RegistryCode), resourceCulture)!; } }
        public static string RequiredField { get { return ResourceManager.GetString(nameof(RequiredField), resourceCulture)!; } }
        public static string Resident { get { return ResourceManager.GetString(nameof(Resident), resourceCulture)!; } }
        public static string Residents { get { return ResourceManager.GetString(nameof(Residents), resourceCulture)!; } }
        public static string Role { get { return ResourceManager.GetString(nameof(Role), resourceCulture)!; } }
        public static string Roles { get { return ResourceManager.GetString(nameof(Roles), resourceCulture)!; } }
        public static string Save { get { return ResourceManager.GetString(nameof(Save), resourceCulture)!; } }
        public static string SaveChanges { get { return ResourceManager.GetString(nameof(SaveChanges), resourceCulture)!; } }
        public static string Scheduled { get { return ResourceManager.GetString(nameof(Scheduled), resourceCulture)!; } }
        public static string ScheduledWork { get { return ResourceManager.GetString(nameof(ScheduledWork), resourceCulture)!; } }
        public static string Search { get { return ResourceManager.GetString(nameof(Search), resourceCulture)!; } }
        public static string SearchText { get { return ResourceManager.GetString(nameof(SearchText), resourceCulture)!; } }
        public static string Slug { get { return ResourceManager.GetString(nameof(Slug), resourceCulture)!; } }
        public static string Status { get { return ResourceManager.GetString(nameof(Status), resourceCulture)!; } }
        public static string StringLengthMax { get { return ResourceManager.GetString(nameof(StringLengthMax), resourceCulture)!; } }
        public static string ThisLookupItemWillBeDeleted { get { return ResourceManager.GetString(nameof(ThisLookupItemWillBeDeleted), resourceCulture)!; } }
        public static string Ticket { get { return ResourceManager.GetString(nameof(Ticket), resourceCulture)!; } }
        public static string TicketNumber { get { return ResourceManager.GetString(nameof(TicketNumber), resourceCulture)!; } }
        public static string Tickets { get { return ResourceManager.GetString(nameof(Tickets), resourceCulture)!; } }
        public static string TicketsMonitor { get { return ResourceManager.GetString(nameof(TicketsMonitor), resourceCulture)!; } }
        public static string Title { get { return ResourceManager.GetString(nameof(Title), resourceCulture)!; } }
        public static string TotalCompanies { get { return ResourceManager.GetString(nameof(TotalCompanies), resourceCulture)!; } }
        public static string Unit { get { return ResourceManager.GetString(nameof(Unit), resourceCulture)!; } }
        public static string UnableToCreateLookup { get { return ResourceManager.GetString(nameof(UnableToCreateLookup), resourceCulture)!; } }
        public static string UnableToDeleteLookup { get { return ResourceManager.GetString(nameof(UnableToDeleteLookup), resourceCulture)!; } }
        public static string UnableToLockUser { get { return ResourceManager.GetString(nameof(UnableToLockUser), resourceCulture)!; } }
        public static string UnableToUnlockUser { get { return ResourceManager.GetString(nameof(UnableToUnlockUser), resourceCulture)!; } }
        public static string UnableToUpdateCompany { get { return ResourceManager.GetString(nameof(UnableToUpdateCompany), resourceCulture)!; } }
        public static string UnableToUpdateLookup { get { return ResourceManager.GetString(nameof(UnableToUpdateLookup), resourceCulture)!; } }
        public static string Units { get { return ResourceManager.GetString(nameof(Units), resourceCulture)!; } }
        public static string UnlockUser { get { return ResourceManager.GetString(nameof(UnlockUser), resourceCulture)!; } }
        public static string UserLockedSuccessfully { get { return ResourceManager.GetString(nameof(UserLockedSuccessfully), resourceCulture)!; } }
        public static string UserUnlockedSuccessfully { get { return ResourceManager.GetString(nameof(UserUnlockedSuccessfully), resourceCulture)!; } }
        public static string Users { get { return ResourceManager.GetString(nameof(Users), resourceCulture)!; } }
        public static string ValidFrom { get { return ResourceManager.GetString(nameof(ValidFrom), resourceCulture)!; } }
        public static string ValidTo { get { return ResourceManager.GetString(nameof(ValidTo), resourceCulture)!; } }
        public static string VatNumber { get { return ResourceManager.GetString(nameof(VatNumber), resourceCulture)!; } }
        public static string Vendor { get { return ResourceManager.GetString(nameof(Vendor), resourceCulture)!; } }
        public static string Vendors { get { return ResourceManager.GetString(nameof(Vendors), resourceCulture)!; } }
        public static string WorkLogs { get { return ResourceManager.GetString(nameof(WorkLogs), resourceCulture)!; } }
        public static string WorkToday { get { return ResourceManager.GetString(nameof(WorkToday), resourceCulture)!; } }
        public static string Yes { get { return ResourceManager.GetString(nameof(Yes), resourceCulture)!; } }
    }
}
