//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Views.UiText", typeof(UiText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this page in the current company context..
        /// </summary>
        public static string AccessDeniedDescription {
            get {
                return ResourceManager.GetString("AccessDeniedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access request approved and membership created..
        /// </summary>
        public static string AccessRequestApproved {
            get {
                return ResourceManager.GetString("AccessRequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access request rejected..
        /// </summary>
        public static string AccessRequestRejected {
            get {
                return ResourceManager.GetString("AccessRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} active records.
        /// </summary>
        public static string ActiveRecords {
            get {
                return ResourceManager.GetString("ActiveRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add company user.
        /// </summary>
        public static string AddCompanyUser {
            get {
                return ResourceManager.GetString("AddCompanyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an existing application user by email. This only creates company membership access and does not create a global account..
        /// </summary>
        public static string AddCompanyUserDescription {
            get {
                return ResourceManager.GetString("AddCompanyUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Login.
        /// </summary>
        public static string AlreadyHaveAccountLogin {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already a member of this management company..
        /// </summary>
        public static string AlreadyMemberOfThisManagementCompany {
            get {
                return ResourceManager.GetString("AlreadyMemberOfThisManagementCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve this access request?.
        /// </summary>
        public static string ApproveAccessRequestConfirm {
            get {
                return ResourceManager.GetString("ApproveAccessRequestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to users.
        /// </summary>
        public static string BackToUsers {
            get {
                return ResourceManager.GetString("BackToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how you want to continue.
        /// </summary>
        public static string ChooseHowToContinue {
            get {
                return ResourceManager.GetString("ChooseHowToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company access management.
        /// </summary>
        public static string CompanyAccessManagement {
            get {
                return ResourceManager.GetString("CompanyAccessManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company membership.
        /// </summary>
        public static string CompanyMembership {
            get {
                return ResourceManager.GetString("CompanyMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company registry code.
        /// </summary>
        public static string CompanyRegistryCode {
            get {
                return ResourceManager.GetString("CompanyRegistryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company user added successfully..
        /// </summary>
        public static string CompanyUserAddedSuccessfully {
            get {
                return ResourceManager.GetString("CompanyUserAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company user removed successfully..
        /// </summary>
        public static string CompanyUserRemovedSuccessfully {
            get {
                return ResourceManager.GetString("CompanyUserRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company user updated successfully..
        /// </summary>
        public static string CompanyUserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("CompanyUserUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and continue.
        /// </summary>
        public static string CreateAndContinue {
            get {
                return ResourceManager.GetString("CreateAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This creates a company profile and links your user as the initial management member..
        /// </summary>
        public static string CreateCompanyDescription {
            get {
                return ResourceManager.GetString("CreateCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create management company.
        /// </summary>
        public static string CreateManagementCompany {
            get {
                return ResourceManager.GetString("CreateManagementCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your management company.
        /// </summary>
        public static string CreateYourManagementCompany {
            get {
                return ResourceManager.GetString("CreateYourManagementCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current owner.
        /// </summary>
        public static string CurrentOwner {
            get {
                return ResourceManager.GetString("CurrentOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current users.
        /// </summary>
        public static string CurrentUsers {
            get {
                return ResourceManager.GetString("CurrentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only users in the current company scope are shown here..
        /// </summary>
        public static string CurrentUsersDescription {
            get {
                return ResourceManager.GetString("CurrentUsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This area layout is in place. Dashboard content is currently in progress..
        /// </summary>
        public static string DashboardInProgress {
            get {
                return ResourceManager.GetString("DashboardInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        public static string DevelopmentMode {
            get {
                return ResourceManager.GetString("DevelopmentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update company membership details for {0}..
        /// </summary>
        public static string EditUserDescription {
            get {
                return ResourceManager.GetString("EditUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account or log in to continue..
        /// </summary>
        public static string FlowInfoCreateAccountOrLogin {
            get {
                return ResourceManager.GetString("FlowInfoCreateAccountOrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to context chooser.
        /// </summary>
        public static string GoToContextChooser {
            get {
                return ResourceManager.GetString("GoToContextChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to home.
        /// </summary>
        public static string GoToHome {
            get {
                return ResourceManager.GetString("GoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management company employee onboarding.
        /// </summary>
        public static string HeadingJoinManagementCompany {
            get {
                return ResourceManager.GetString("HeadingJoinManagementCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident onboarding.
        /// </summary>
        public static string HeadingResidentOnboarding {
            get {
                return ResourceManager.GetString("HeadingResidentOnboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home placeholder.
        /// </summary>
        public static string HomePlaceholder {
            get {
                return ResourceManager.GetString("HomePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join an existing management company account..
        /// </summary>
        public static string JoinExistingManagement {
            get {
                return ResourceManager.GetString("JoinExistingManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join request is already resolved..
        /// </summary>
        public static string JoinRequestAlreadyResolved {
            get {
                return ResourceManager.GetString("JoinRequestAlreadyResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join request not found..
        /// </summary>
        public static string JoinRequestNotFound {
            get {
                return ResourceManager.GetString("JoinRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join request submitted. Please wait for management company approval..
        /// </summary>
        public static string JoinRequestSubmitted {
            get {
                return ResourceManager.GetString("JoinRequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Area.
        /// </summary>
        public static string ManagementArea {
            get {
                return ResourceManager.GetString("ManagementArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management company was not found..
        /// </summary>
        public static string ManagementCompanyWasNotFound {
            get {
                return ResourceManager.GetString("ManagementCompanyWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management dashboard.
        /// </summary>
        public static string ManagementDashboard {
            get {
                return ResourceManager.GetString("ManagementDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management company employee.
        /// </summary>
        public static string ManagementEmployeeOnboarding {
            get {
                return ResourceManager.GetString("ManagementEmployeeOnboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Workspace.
        /// </summary>
        public static string ManagementWorkspace {
            get {
                return ResourceManager.GetString("ManagementWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message (optional).
        /// </summary>
        public static string MessageOptional {
            get {
                return ResourceManager.GetString("MessageOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need an account? Register.
        /// </summary>
        public static string NeedAccountRegister {
            get {
                return ResourceManager.GetString("NeedAccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New context.
        /// </summary>
        public static string NewContext {
            get {
                return ResourceManager.GetString("NewContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New management company.
        /// </summary>
        public static string NewManagementCompany {
            get {
                return ResourceManager.GetString("NewManagementCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New owner.
        /// </summary>
        public static string NewOwner {
            get {
                return ResourceManager.GetString("NewOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New owner is required..
        /// </summary>
        public static string NewOwnerRequired {
            get {
                return ResourceManager.GetString("NewOwnerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No company contexts.
        /// </summary>
        public static string NoCompanyContexts {
            get {
                return ResourceManager.GetString("NoCompanyContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No company users found.
        /// </summary>
        public static string NoCompanyUsersFound {
            get {
                return ResourceManager.GetString("NoCompanyUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the first company member by email to grant access..
        /// </summary>
        public static string NoCompanyUsersFoundDescription {
            get {
                return ResourceManager.GetString("NoCompanyUsersFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer contexts.
        /// </summary>
        public static string NoCustomerContexts {
            get {
                return ResourceManager.GetString("NoCustomerContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pending requests.
        /// </summary>
        public static string NoPendingRequests {
            get {
                return ResourceManager.GetString("NoPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no pending access requests for this company..
        /// </summary>
        public static string NoPendingRequestsDescription {
            get {
                return ResourceManager.GetString("NoPendingRequestsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to resolve access requests..
        /// </summary>
        public static string NoPermissionToResolveAccessRequests {
            get {
                return ResourceManager.GetString("NoPermissionToResolveAccessRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resident context.
        /// </summary>
        public static string NoResidentContext {
            get {
                return ResourceManager.GetString("NoResidentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not currently effective.
        /// </summary>
        public static string NotCurrentlyEffective {
            get {
                return ResourceManager.GetString("NotCurrentlyEffective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding.
        /// </summary>
        public static string Onboarding {
            get {
                return ResourceManager.GetString("Onboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner role cannot be assigned, edited, or removed in generic user flows. Use the dedicated ownership transfer workflow instead..
        /// </summary>
        public static string OwnerRoleManagedThroughTransfer {
            get {
                return ResourceManager.GetString("OwnerRoleManagedThroughTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership transferred successfully..
        /// </summary>
        public static string OwnershipTransferredSuccessfully {
            get {
                return ResourceManager.GetString("OwnershipTransferredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the current owner can transfer ownership..
        /// </summary>
        public static string OwnershipTransferRequiresCurrentOwner {
            get {
                return ResourceManager.GetString("OwnershipTransferRequiresCurrentOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending access requests.
        /// </summary>
        public static string PendingAccessRequests {
            get {
                return ResourceManager.GetString("PendingAccessRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and decide pending employee onboarding access requests for this company..
        /// </summary>
        public static string PendingAccessRequestsDescription {
            get {
                return ResourceManager.GetString("PendingAccessRequestsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pending request for this company already exists..
        /// </summary>
        public static string PendingRequestForThisCompanyAlreadyExists {
            get {
                return ResourceManager.GetString("PendingRequestForThisCompanyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your company..
        /// </summary>
        public static string RegisterYourCompany {
            get {
                return ResourceManager.GetString("RegisterYourCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful. Please log in..
        /// </summary>
        public static string RegistrationSuccessfulPleaseLogin {
            get {
                return ResourceManager.GetString("RegistrationSuccessfulPleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry code.
        /// </summary>
        public static string RegistryCode {
            get {
                return ResourceManager.GetString("RegistryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject this access request?.
        /// </summary>
        public static string RejectAccessRequestConfirm {
            get {
                return ResourceManager.GetString("RejectAccessRequestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this user from the company?.
        /// </summary>
        public static string RemoveUserFromCompanyConfirm {
            get {
                return ResourceManager.GetString("RemoveUserFromCompanyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested at.
        /// </summary>
        public static string RequestedAt {
            get {
                return ResourceManager.GetString("RequestedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested role.
        /// </summary>
        public static string RequestedRole {
            get {
                return ResourceManager.GetString("RequestedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested role is required..
        /// </summary>
        public static string RequestedRoleRequired {
            get {
                return ResourceManager.GetString("RequestedRoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester is already a member of this company..
        /// </summary>
        public static string RequesterAlreadyMemberOfThisCompany {
            get {
                return ResourceManager.GetString("RequesterAlreadyMemberOfThisCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID.
        /// </summary>
        public static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident.
        /// </summary>
        public static string Resident {
            get {
                return ResourceManager.GetString("Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident Dashboard.
        /// </summary>
        public static string ResidentDashboard {
            get {
                return ResourceManager.GetString("ResidentDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This flow is not part of the current slice and is intentionally left as a placeholder..
        /// </summary>
        public static string ResidentOnboardingDescription {
            get {
                return ResourceManager.GetString("ResidentOnboardingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request access to your resident dashboard..
        /// </summary>
        public static string ResidentRequestAccess {
            get {
                return ResourceManager.GetString("ResidentRequestAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected role is invalid..
        /// </summary>
        public static string SelectedRoleIsInvalid {
            get {
                return ResourceManager.GetString("SelectedRoleIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new owner.
        /// </summary>
        public static string SelectNewOwner {
            get {
                return ResourceManager.GetString("SelectNewOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select role.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up your access to enter the platform..
        /// </summary>
        public static string SetupAccessPrompt {
            get {
                return ResourceManager.GetString("SetupAccessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start setup.
        /// </summary>
        public static string StartSetup {
            get {
                return ResourceManager.GetString("StartSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a minimum length of {2} and a maximum length of {1}..
        /// </summary>
        public static string StringLengthBetween {
            get {
                return ResourceManager.GetString("StringLengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit join request.
        /// </summary>
        public static string SubmitJoinRequest {
            get {
                return ResourceManager.GetString("SubmitJoinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join management company.
        /// </summary>
        public static string TitleJoinManagementCompany {
            get {
                return ResourceManager.GetString("TitleJoinManagementCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident access.
        /// </summary>
        public static string TitleResidentAccess {
            get {
                return ResourceManager.GetString("TitleResidentAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer ownership.
        /// </summary>
        public static string TransferOwnership {
            get {
                return ResourceManager.GetString("TransferOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer company ownership to the selected member?.
        /// </summary>
        public static string TransferOwnershipConfirm {
            get {
                return ResourceManager.GetString("TransferOwnershipConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer company ownership for {0} to another active effective company member..
        /// </summary>
        public static string TransferOwnershipDescription {
            get {
                return ResourceManager.GetString("TransferOwnershipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected member will become the new owner. The current owner will be changed to manager automatically..
        /// </summary>
        public static string TransferOwnershipHelpText {
            get {
                return ResourceManager.GetString("TransferOwnershipHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user..
        /// </summary>
        public static string UnableToAddUser {
            get {
                return ResourceManager.GetString("UnableToAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to approve access request..
        /// </summary>
        public static string UnableToApproveAccessRequest {
            get {
                return ResourceManager.GetString("UnableToApproveAccessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reject access request..
        /// </summary>
        public static string UnableToRejectAccessRequest {
            get {
                return ResourceManager.GetString("UnableToRejectAccessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove company user..
        /// </summary>
        public static string UnableToRemoveCompanyUser {
            get {
                return ResourceManager.GetString("UnableToRemoveCompanyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit join request..
        /// </summary>
        public static string UnableToSubmitJoinRequest {
            get {
                return ResourceManager.GetString("UnableToSubmitJoinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to transfer ownership..
        /// </summary>
        public static string UnableToTransferOwnership {
            get {
                return ResourceManager.GetString("UnableToTransferOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update user..
        /// </summary>
        public static string UnableToUpdateUser {
            get {
                return ResourceManager.GetString("UnableToUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage members who belong to {0}, update company-level access, and prepare for future pending access requests..
        /// </summary>
        public static string UsersPageIntro {
            get {
                return ResourceManager.GetString("UsersPageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid to.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT number.
        /// </summary>
        public static string VatNumber {
            get {
                return ResourceManager.GetString("VatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
