/* ------------------------------------------------------------
   PostgreSQL translation of your cleaned script
   - TINYINT      -> BOOLEAN
   - BLOB         -> BYTEA
   - TIMESTAMP(0) -> TIMESTAMP(0) WITHOUT TIME ZONE
   - Kept names/casing as-is (including BILLING_AADRESS)
   ------------------------------------------------------------ */

--------------------------------------------------------------
-- Table Creation --
--------------------------------------------------------------

CREATE TABLE APPUSER(
	USER_ID               INTEGER NOT NULL,
	FIRST_NAME            VARCHAR(100) NOT NULL,
	LAST_NAME             VARCHAR(100) NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	LAST_LOGIN_AT         TIMESTAMP(0) WITHOUT TIME ZONE,
	IS_ACTIVE             BOOLEAN NOT NULL,
	CLOSED_AT             TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	IDENTITYUSER_ID_FK    INTEGER NOT NULL,
	CONSTRAINT pk_APPUSER PRIMARY KEY (USER_ID),
	CONSTRAINT uq_APPUSER_IDENTITYUSER UNIQUE (IDENTITYUSER_ID_FK)
);

CREATE TABLE MANAGMENT_COMPANY(
	MANAGEMENT_COMPANY_ID INTEGER NOT NULL,
	NAME                  VARCHAR(200) NOT NULL,
	REGISTRY_CODE         VARCHAR(255) NOT NULL UNIQUE,
	VAT_NUMBER            VARCHAR(50) NOT NULL,
	EMAIL                 VARCHAR(200) NOT NULL,
	PHONE                 VARCHAR(50) NOT NULL,
	ADDRESS               VARCHAR(300) NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	IS_ACTIVE             BOOLEAN NOT NULL,
	CONSTRAINT pk_MANAGMENT_COMPANY PRIMARY KEY (MANAGEMENT_COMPANY_ID)
);

CREATE TABLE MCOMPANY_USER(
	MCOMPANY_USER_ID      INTEGER NOT NULL,
	VALID_FROM            DATE NOT NULL,
	VALID_TO              DATE,
	JOB_TITLE             VARCHAR(255) NOT NULL,
	IS_ACTIVE             BOOLEAN NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	MCOMPANY_ID_FK        INTEGER NOT NULL,
	APPUSER_ID_FK         INTEGER NOT NULL,
	MCOMPANY_ROLE_ID_FK   INTEGER NOT NULL,
	CONSTRAINT pk_MCOMPANY_USER PRIMARY KEY (MCOMPANY_USER_ID)
);

CREATE TABLE CUSTOMER(
	CUSTOMER_ID           INTEGER NOT NULL,
	NAME                  VARCHAR(200) NOT NULL,
	REGISTRY_CODE         VARCHAR(50) NOT NULL,
	BILLING_EMAIL         VARCHAR(200),
	BILLING_AADRESS       VARCHAR(255),
	PHONE                 VARCHAR(50),
	NOTES                 BYTEA,
	IS_ACTIVE             BOOLEAN NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	MCOMPANY_ID_FK        INTEGER NOT NULL,
	CONSTRAINT pk_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE RESIDENT(
	RESIDENT_ID           INTEGER NOT NULL,
	FIRST_NAME            VARCHAR(100) NOT NULL,
	LAST_NAME             VARCHAR(100) NOT NULL,
	ID_CODE               VARCHAR(20),
	PREFERRED_LANGUAGE    VARCHAR(20),
	IS_ACTIVE             BOOLEAN NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	MCOMPANY_ID_FK        INTEGER NOT NULL,
	CONSTRAINT pk_RESIDENT PRIMARY KEY (RESIDENT_ID)
);

CREATE TABLE RESIDENT_USER(
	RESIDENT_USER_ID      INTEGER NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	IS_ACTIVE             BOOLEAN NOT NULL,
	VALID_FROM            DATE NOT NULL,
	VALID_TO              DATE,
	APPUSER_ID_FK         INTEGER NOT NULL,
	RESIDENT_ID_FK        INTEGER NOT NULL,
	CONSTRAINT pk_RESIDENT_USER PRIMARY KEY (RESIDENT_USER_ID)
);

CREATE TABLE PROPERTY(
	PROPERTY_ID           INTEGER NOT NULL,
	LABEL                 VARCHAR(200) NOT NULL,
	ADDRESS_LINE          VARCHAR(255) NOT NULL,
	CITY                  VARCHAR(100) NOT NULL,
	POSTAL_CODE           VARCHAR(20) NOT NULL,
	NOTES                 BYTEA,
	IS_ACTIVE             BOOLEAN NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	PROPERTY_TYPE_ID_FK   INTEGER NOT NULL,
	CUSTOMER_ID_FK        INTEGER NOT NULL,
	CONSTRAINT pk_PROPERTY PRIMARY KEY (PROPERTY_ID)
);

CREATE TABLE UNIT(
	UNIT_ID               INTEGER NOT NULL,
	UNIT_NR               VARCHAR(50) NOT NULL,
	FLOOR_NR              INTEGER,
	SIZE_M2               NUMERIC(10,2),
	NOTES                 BYTEA,
	IS_ACTIVE             BOOLEAN NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	PROPERTY_ID_FK        INTEGER NOT NULL,
	CONSTRAINT pk_UNIT PRIMARY KEY (UNIT_ID)
);

CREATE TABLE CUSTOMER_REPRESENTATIVE(
	CUSTOMER_REPRESENTATIVE_ID        INTEGER NOT NULL,
	VALID_FROM                        DATE NOT NULL,
	VALID_TO                          DATE,
	IS_ACTIVE                         BOOLEAN NOT NULL,
	CREATED_AT                        TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	NOTES                             BYTEA,
	CUSTOMER_REPRESENTATIVE_ROLE_ID_FK INTEGER NOT NULL,
	CUSTOMER_ID_FK                    INTEGER NOT NULL,
	RESIDENT_ID_FK                    INTEGER NOT NULL,
	CONSTRAINT pk_CUSTOMER_REPRESENTATIVE PRIMARY KEY (CUSTOMER_REPRESENTATIVE_ID)
);

CREATE TABLE CUSTOMER_REPRESENTATIVE_ROLE(
	CUSTOMER_REPRESENTATIVE_ROLE_ID   INTEGER NOT NULL,
	CODE                              VARCHAR(20) NOT NULL,
	LABEL                             VARCHAR(255) NOT NULL,
	CONSTRAINT pk_CUSTOMER_REPRESENTATIVE_ROLE PRIMARY KEY (CUSTOMER_REPRESENTATIVE_ROLE_ID),
	CONSTRAINT uq_CUSTOMER_REPRESENTATIVE_ROLE_CODE UNIQUE (CODE)
);

CREATE TABLE IDENTITYUSER(
	IDENTITYUSER_ID       INTEGER NOT NULL,
	CONSTRAINT pk_IDENTITYUSER PRIMARY KEY (IDENTITYUSER_ID)
);

CREATE TABLE LEASE(
	LEASE_ID              INTEGER NOT NULL,
	START_DATE            DATE NOT NULL,
	END_DATE              DATE,
	IS_ACTIVE             BOOLEAN NOT NULL,
	NOTES                 BYTEA,
	LEASE_ROLE_ID_FK      INTEGER NOT NULL,
	UNIT_ID_FK            INTEGER NOT NULL,
	RESIDENT_ID_FK        INTEGER NOT NULL,
	CONSTRAINT pk_LEASE PRIMARY KEY (LEASE_ID)
);

CREATE TABLE VENDOR(
	VENDOR_ID             INTEGER NOT NULL,
	NAME                  VARCHAR(200) NOT NULL,
	REGISTRY_CODE         VARCHAR(50) NOT NULL,
	NOTES                 BYTEA NOT NULL,
	IS_ACTIVE             BOOLEAN NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	MCOMPANY_ID_FK        INTEGER NOT NULL,
	CONSTRAINT pk_VENDOR PRIMARY KEY (VENDOR_ID)
);

CREATE TABLE VENDOR_CONTACT(
	VENDOR_CONTACT_ID     INTEGER NOT NULL,
	VALID_FROM            DATE NOT NULL,
	VALID_TO              DATE,
	CONFIRMED             BOOLEAN NOT NULL,
	IS_PRIMARY            BOOLEAN NOT NULL,
	FULL_NAME             VARCHAR(200),
	ROLE_TITLE            VARCHAR(200),
	CONTACT_ID_FK         INTEGER NOT NULL,
	VENDOR_ID_FK          INTEGER NOT NULL,
	CONSTRAINT pk_VENDOR_CONTACT PRIMARY KEY (VENDOR_CONTACT_ID)
);

CREATE TABLE CONTACT(
	CONTACT_ID            INTEGER NOT NULL,
	CONTACT_VALUE         VARCHAR(255) NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	NOTES                 BYTEA,
	CONTACT_TYPE_ID_FK    INTEGER NOT NULL,
	MCOMPANY_ID_FK        INTEGER NOT NULL,
	CONSTRAINT pk_CONTACT PRIMARY KEY (CONTACT_ID)
);

CREATE TABLE CONTACT_TYPE(
	CONTACT_TYPE_ID       INTEGER NOT NULL,
	CODE                  VARCHAR(20) NOT NULL,
	LABEL                 VARCHAR(255) NOT NULL,
	CONSTRAINT pk_CONTACT_TYPE PRIMARY KEY (CONTACT_TYPE_ID),
	CONSTRAINT uq_CONTACT_TYPE_CODE UNIQUE (CODE)
);

CREATE TABLE RESIDENT_CONTACT(
	RESIDENT_CONTACT_ID   INTEGER NOT NULL,
	VALID_FROM            DATE NOT NULL,
	VALID_TO              DATE,
	CONFIRMED             BOOLEAN NOT NULL,
	IS_PRIMARY            BOOLEAN NOT NULL,
	RESIDENT_ID_FK        INTEGER NOT NULL,
	CONTACT_ID_FK         INTEGER NOT NULL,
	CONSTRAINT pk_RESIDENT_CONTACT PRIMARY KEY (RESIDENT_CONTACT_ID)
);

CREATE TABLE TICKET(
	TICKET_ID             INTEGER NOT NULL,
	TICKET_NR             VARCHAR(20) NOT NULL,
	TITLE                 VARCHAR(255) NOT NULL,
	DESCRIPTION           BYTEA NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	DUE_AT                TIMESTAMP(0) WITHOUT TIME ZONE,
	CLOSED_AT             TIMESTAMP(0) WITHOUT TIME ZONE,
	MCOMPANY_ID_FK        INTEGER NOT NULL,
	CUSTOMER_ID_FK        INTEGER,
	RESIDENT_ID_FK        INTEGER,
	PROPERTY_ID_FK        INTEGER,
	UNIT_ID_FK            INTEGER,
	TICKET_CATEGORY_ID_FK INTEGER,
	VENDOR_ID_FK          INTEGER,
	TICKET_STATUS_ID_FK   INTEGER NOT NULL,
	TICKET_PRIORITY_ID_FK INTEGER NOT NULL,
	CONSTRAINT pk_TICKET PRIMARY KEY (TICKET_ID)
);

CREATE TABLE TICKET_CATEGORY(
	TICKET_CATEGORY_ID    INTEGER NOT NULL,
	CODE                  VARCHAR(50) NOT NULL,
	LABEL                 VARCHAR(255) NOT NULL,
	CONSTRAINT pk_TICKET_CATEGORY PRIMARY KEY (TICKET_CATEGORY_ID),
	CONSTRAINT uq_TICKET_CATEGORY_CODE UNIQUE (CODE)
);

CREATE TABLE VENDOR_TICKET_CATEGORY(
	VENDOR_TICKET_CATEGORY_ID INTEGER NOT NULL,
	NOTES                 BYTEA,
	IS_ACTIVE             BOOLEAN NOT NULL,
	VENDOR_ID_FK          INTEGER NOT NULL,
	TICKET_CATEGORY_ID_FK INTEGER NOT NULL,
	CONSTRAINT pk_VENDOR_TICKET_CATEGORY PRIMARY KEY (VENDOR_TICKET_CATEGORY_ID)
);

CREATE TABLE MCOMPANY_ROLE(
	MCOMPANY_ROLE_ID      INTEGER NOT NULL,
	CODE                  VARCHAR(100) NOT NULL,
	LABEL                 VARCHAR(255) NOT NULL,
	CONSTRAINT pk_MCOMPANY_ROLE PRIMARY KEY (MCOMPANY_ROLE_ID),
	CONSTRAINT uq_MCOMPANY_ROLE_CODE UNIQUE (CODE),
	CONSTRAINT uq_MCOMPANY_ROLE_LABEL UNIQUE (LABEL)
);

CREATE TABLE LEASE_ROLE(
	LEASE_ROLE_ID         INTEGER NOT NULL,
	CODE                  VARCHAR(20) NOT NULL,
	LABEL                 VARCHAR(255) NOT NULL,
	CONSTRAINT pk_LEASE_ROLE PRIMARY KEY (LEASE_ROLE_ID)
);

CREATE TABLE SCHEDULED_WORK(
	SCHEDULED_WORK_ID     INTEGER NOT NULL,
	SCHEDULED_START       TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	SCHEDULED_END         TIMESTAMP(0) WITHOUT TIME ZONE,
	REAL_START            TIMESTAMP(0) WITHOUT TIME ZONE,
	REAL_END              TIMESTAMP(0) WITHOUT TIME ZONE,
	NOTES                 BYTEA,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	VENDOR_ID_FK          INTEGER NOT NULL,
	TICKET_ID_FK          INTEGER NOT NULL,
	WORK_STATUS_ID_FK     INTEGER NOT NULL,
	CONSTRAINT pk_SCHEDULED_WORK PRIMARY KEY (SCHEDULED_WORK_ID)
);

CREATE TABLE WORK_LOG(
	WORK_LOG_ID           INTEGER NOT NULL,
	CREATED_AT            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	WORK_START            TIMESTAMP(0) WITHOUT TIME ZONE,
	WORK_END              TIMESTAMP(0) WITHOUT TIME ZONE,
	HOURS                 NUMERIC(10,2),
	MATERIAL_COST         NUMERIC(10,2),
	LABOR_COST            NUMERIC(10,2),
	DESCRIPTION           BYTEA,
	APPUSER_ID_FK         INTEGER NOT NULL,
	SCHEDULED_WORK_ID_FK  INTEGER NOT NULL,
	CONSTRAINT pk_WORK_LOG PRIMARY KEY (WORK_LOG_ID)
);

CREATE TABLE PROPERTY_TYPE(
	PROPERTY_TYPE_ID      INTEGER NOT NULL,
	CODE                  VARCHAR(100) NOT NULL,
	LABEL                 VARCHAR(255) NOT NULL,
	CONSTRAINT pk_PROPERTY_TYPE PRIMARY KEY (PROPERTY_TYPE_ID),
	CONSTRAINT uq_PROPERTY_TYPE_CODE UNIQUE (CODE)
);

CREATE TABLE TICKET_STATUS(
	TICKET_STATUS_ID      INTEGER NOT NULL,
	CODE                  VARCHAR(50) NOT NULL,
	LABEL                 VARCHAR(100) NOT NULL,
	CONSTRAINT pk_TICKET_STATUS PRIMARY KEY (TICKET_STATUS_ID)
);

CREATE TABLE TICKET_PRIORITY(
	TICKET_PRIORITY_ID    INTEGER NOT NULL,
	CODE                  VARCHAR(20) NOT NULL,
	LABEL                 VARCHAR(100) NOT NULL,
	CONSTRAINT pk_TICKET_PRIORITY PRIMARY KEY (TICKET_PRIORITY_ID)
);

CREATE TABLE WORK_STATUS(
	WORK_STATUS_ID        INTEGER NOT NULL,
	CODE                  VARCHAR(50) NOT NULL,
	LABEL                 VARCHAR(255) NOT NULL,
	CONSTRAINT pk_WORK_STATUS PRIMARY KEY (WORK_STATUS_ID),
	CONSTRAINT uq_WORK_STATUS_CODE UNIQUE (CODE)
);

--------------------------------------------------------------
-- Foreign Key Constraints for *_FK columns
--------------------------------------------------------------

ALTER TABLE APPUSER
	ADD CONSTRAINT fk_appuser_identityuser
	FOREIGN KEY (IDENTITYUSER_ID_FK) REFERENCES IDENTITYUSER(IDENTITYUSER_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MCOMPANY_USER
	ADD CONSTRAINT fk_mcompany_user_mcompany
	FOREIGN KEY (MCOMPANY_ID_FK) REFERENCES MANAGMENT_COMPANY(MANAGEMENT_COMPANY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MCOMPANY_USER
	ADD CONSTRAINT fk_mcompany_user_appuser
	FOREIGN KEY (APPUSER_ID_FK) REFERENCES APPUSER(USER_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MCOMPANY_USER
	ADD CONSTRAINT fk_mcompany_user_role
	FOREIGN KEY (MCOMPANY_ROLE_ID_FK) REFERENCES MCOMPANY_ROLE(MCOMPANY_ROLE_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CUSTOMER
	ADD CONSTRAINT fk_customer_mcompany
	FOREIGN KEY (MCOMPANY_ID_FK) REFERENCES MANAGMENT_COMPANY(MANAGEMENT_COMPANY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RESIDENT
	ADD CONSTRAINT fk_resident_mcompany
	FOREIGN KEY (MCOMPANY_ID_FK) REFERENCES MANAGMENT_COMPANY(MANAGEMENT_COMPANY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RESIDENT_USER
	ADD CONSTRAINT fk_resident_user_appuser
	FOREIGN KEY (APPUSER_ID_FK) REFERENCES APPUSER(USER_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RESIDENT_USER
	ADD CONSTRAINT fk_resident_user_resident
	FOREIGN KEY (RESIDENT_ID_FK) REFERENCES RESIDENT(RESIDENT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PROPERTY
	ADD CONSTRAINT fk_property_type
	FOREIGN KEY (PROPERTY_TYPE_ID_FK) REFERENCES PROPERTY_TYPE(PROPERTY_TYPE_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PROPERTY
	ADD CONSTRAINT fk_property_customer
	FOREIGN KEY (CUSTOMER_ID_FK) REFERENCES CUSTOMER(CUSTOMER_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE UNIT
	ADD CONSTRAINT fk_unit_property
	FOREIGN KEY (PROPERTY_ID_FK) REFERENCES PROPERTY(PROPERTY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CUSTOMER_REPRESENTATIVE
	ADD CONSTRAINT fk_custrep_role
	FOREIGN KEY (CUSTOMER_REPRESENTATIVE_ROLE_ID_FK) REFERENCES CUSTOMER_REPRESENTATIVE_ROLE(CUSTOMER_REPRESENTATIVE_ROLE_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CUSTOMER_REPRESENTATIVE
	ADD CONSTRAINT fk_custrep_customer
	FOREIGN KEY (CUSTOMER_ID_FK) REFERENCES CUSTOMER(CUSTOMER_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CUSTOMER_REPRESENTATIVE
	ADD CONSTRAINT fk_custrep_resident
	FOREIGN KEY (RESIDENT_ID_FK) REFERENCES RESIDENT(RESIDENT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LEASE
	ADD CONSTRAINT fk_lease_role
	FOREIGN KEY (LEASE_ROLE_ID_FK) REFERENCES LEASE_ROLE(LEASE_ROLE_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LEASE
	ADD CONSTRAINT fk_lease_unit
	FOREIGN KEY (UNIT_ID_FK) REFERENCES UNIT(UNIT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE LEASE
	ADD CONSTRAINT fk_lease_resident
	FOREIGN KEY (RESIDENT_ID_FK) REFERENCES RESIDENT(RESIDENT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE VENDOR
	ADD CONSTRAINT fk_vendor_mcompany
	FOREIGN KEY (MCOMPANY_ID_FK) REFERENCES MANAGMENT_COMPANY(MANAGEMENT_COMPANY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE VENDOR_CONTACT
	ADD CONSTRAINT fk_vendor_contact_contact
	FOREIGN KEY (CONTACT_ID_FK) REFERENCES CONTACT(CONTACT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE VENDOR_CONTACT
	ADD CONSTRAINT fk_vendor_contact_vendor
	FOREIGN KEY (VENDOR_ID_FK) REFERENCES VENDOR(VENDOR_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CONTACT
	ADD CONSTRAINT fk_contact_type
	FOREIGN KEY (CONTACT_TYPE_ID_FK) REFERENCES CONTACT_TYPE(CONTACT_TYPE_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CONTACT
	ADD CONSTRAINT fk_contact_mcompany
	FOREIGN KEY (MCOMPANY_ID_FK) REFERENCES MANAGMENT_COMPANY(MANAGEMENT_COMPANY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RESIDENT_CONTACT
	ADD CONSTRAINT fk_resident_contact_resident
	FOREIGN KEY (RESIDENT_ID_FK) REFERENCES RESIDENT(RESIDENT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RESIDENT_CONTACT
	ADD CONSTRAINT fk_resident_contact_contact
	FOREIGN KEY (CONTACT_ID_FK) REFERENCES CONTACT(CONTACT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_mcompany
	FOREIGN KEY (MCOMPANY_ID_FK) REFERENCES MANAGMENT_COMPANY(MANAGEMENT_COMPANY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_customer
	FOREIGN KEY (CUSTOMER_ID_FK) REFERENCES CUSTOMER(CUSTOMER_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_resident
	FOREIGN KEY (RESIDENT_ID_FK) REFERENCES RESIDENT(RESIDENT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_property
	FOREIGN KEY (PROPERTY_ID_FK) REFERENCES PROPERTY(PROPERTY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_unit
	FOREIGN KEY (UNIT_ID_FK) REFERENCES UNIT(UNIT_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_category
	FOREIGN KEY (TICKET_CATEGORY_ID_FK) REFERENCES TICKET_CATEGORY(TICKET_CATEGORY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_vendor
	FOREIGN KEY (VENDOR_ID_FK) REFERENCES VENDOR(VENDOR_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_status
	FOREIGN KEY (TICKET_STATUS_ID_FK) REFERENCES TICKET_STATUS(TICKET_STATUS_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TICKET
	ADD CONSTRAINT fk_ticket_priority
	FOREIGN KEY (TICKET_PRIORITY_ID_FK) REFERENCES TICKET_PRIORITY(TICKET_PRIORITY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE VENDOR_TICKET_CATEGORY
	ADD CONSTRAINT fk_vtc_vendor
	FOREIGN KEY (VENDOR_ID_FK) REFERENCES VENDOR(VENDOR_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE VENDOR_TICKET_CATEGORY
	ADD CONSTRAINT fk_vtc_category
	FOREIGN KEY (TICKET_CATEGORY_ID_FK) REFERENCES TICKET_CATEGORY(TICKET_CATEGORY_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SCHEDULED_WORK
	ADD CONSTRAINT fk_schedwork_vendor
	FOREIGN KEY (VENDOR_ID_FK) REFERENCES VENDOR(VENDOR_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SCHEDULED_WORK
	ADD CONSTRAINT fk_schedwork_ticket
	FOREIGN KEY (TICKET_ID_FK) REFERENCES TICKET(TICKET_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SCHEDULED_WORK
	ADD CONSTRAINT fk_schedwork_status
	FOREIGN KEY (WORK_STATUS_ID_FK) REFERENCES WORK_STATUS(WORK_STATUS_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE WORK_LOG
	ADD CONSTRAINT fk_worklog_appuser
	FOREIGN KEY (APPUSER_ID_FK) REFERENCES APPUSER(USER_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE WORK_LOG
	ADD CONSTRAINT fk_worklog_schedwork
	FOREIGN KEY (SCHEDULED_WORK_ID_FK) REFERENCES SCHEDULED_WORK(SCHEDULED_WORK_ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

-- APPUSER
CREATE INDEX ix_appuser_identityuser_id_fk ON appuser(identityuser_id_fk);

-- MCOMPANY_USER
CREATE INDEX ix_mcompany_user_mcompany_id_fk      ON mcompany_user(mcompany_id_fk);
CREATE INDEX ix_mcompany_user_appuser_id_fk       ON mcompany_user(appuser_id_fk);
CREATE INDEX ix_mcompany_user_mcompany_role_id_fk ON mcompany_user(mcompany_role_id_fk);

-- CUSTOMER
CREATE INDEX ix_customer_mcompany_id_fk ON customer(mcompany_id_fk);

-- RESIDENT
CREATE INDEX ix_resident_mcompany_id_fk ON resident(mcompany_id_fk);

-- RESIDENT_USER
CREATE INDEX ix_resident_user_appuser_id_fk  ON resident_user(appuser_id_fk);
CREATE INDEX ix_resident_user_resident_id_fk ON resident_user(resident_id_fk);

-- PROPERTY
CREATE INDEX ix_property_property_type_id_fk ON property(property_type_id_fk);
CREATE INDEX ix_property_customer_id_fk      ON property(customer_id_fk);

-- UNIT
CREATE INDEX ix_unit_property_id_fk ON unit(property_id_fk);

-- CUSTOMER_REPRESENTATIVE
CREATE INDEX ix_customer_representative_role_id_fk    ON customer_representative(customer_representative_role_id_fk);
CREATE INDEX ix_customer_representative_customer_id_fk ON customer_representative(customer_id_fk);
CREATE INDEX ix_customer_representative_resident_id_fk ON customer_representative(resident_id_fk);

-- LEASE
CREATE INDEX ix_lease_lease_role_id_fk ON lease(lease_role_id_fk);
CREATE INDEX ix_lease_unit_id_fk       ON lease(unit_id_fk);
CREATE INDEX ix_lease_resident_id_fk   ON lease(resident_id_fk);

-- VENDOR
CREATE INDEX ix_vendor_mcompany_id_fk ON vendor(mcompany_id_fk);

-- VENDOR_CONTACT
CREATE INDEX ix_vendor_contact_contact_id_fk ON vendor_contact(contact_id_fk);
CREATE INDEX ix_vendor_contact_vendor_id_fk  ON vendor_contact(vendor_id_fk);

-- CONTACT
CREATE INDEX ix_contact_contact_type_id_fk ON contact(contact_type_id_fk);
CREATE INDEX ix_contact_mcompany_id_fk     ON contact(mcompany_id_fk);

-- RESIDENT_CONTACT
CREATE INDEX ix_resident_contact_resident_id_fk ON resident_contact(resident_id_fk);
CREATE INDEX ix_resident_contact_contact_id_fk  ON resident_contact(contact_id_fk);

-- TICKET
CREATE INDEX ix_ticket_mcompany_id_fk        ON ticket(mcompany_id_fk);
CREATE INDEX ix_ticket_customer_id_fk        ON ticket(customer_id_fk);
CREATE INDEX ix_ticket_resident_id_fk        ON ticket(resident_id_fk);
CREATE INDEX ix_ticket_property_id_fk        ON ticket(property_id_fk);
CREATE INDEX ix_ticket_unit_id_fk            ON ticket(unit_id_fk);
CREATE INDEX ix_ticket_ticket_category_id_fk ON ticket(ticket_category_id_fk);
CREATE INDEX ix_ticket_vendor_id_fk          ON ticket(vendor_id_fk);
CREATE INDEX ix_ticket_ticket_status_id_fk   ON ticket(ticket_status_id_fk);
CREATE INDEX ix_ticket_ticket_priority_id_fk ON ticket(ticket_priority_id_fk);

-- VENDOR_TICKET_CATEGORY
CREATE INDEX ix_vtc_vendor_id_fk   ON vendor_ticket_category(vendor_id_fk);
CREATE INDEX ix_vtc_category_id_fk ON vendor_ticket_category(ticket_category_id_fk);

-- SCHEDULED_WORK
CREATE INDEX ix_scheduled_work_vendor_id_fk      ON scheduled_work(vendor_id_fk);
CREATE INDEX ix_scheduled_work_ticket_id_fk      ON scheduled_work(ticket_id_fk);
CREATE INDEX ix_scheduled_work_work_status_id_fk ON scheduled_work(work_status_id_fk);

-- WORK_LOG
CREATE INDEX ix_work_log_appuser_id_fk        ON work_log(appuser_id_fk);
CREATE INDEX ix_work_log_scheduled_work_id_fk ON work_log(scheduled_work_id_fk);

-- Ticket list screens: by company + status, ordered by created_at
CREATE INDEX ix_ticket_company_status_created_at
ON ticket(mcompany_id_fk, ticket_status_id_fk, created_at DESC);

-- Ticket list screens: by vendor + status (if vendors use a queue)
CREATE INDEX ix_ticket_vendor_status_created_at
ON ticket(vendor_id_fk, ticket_status_id_fk, created_at DESC);

-- Scheduled work calendar: vendor + scheduled_start
CREATE INDEX ix_scheduled_work_vendor_scheduled_start
ON scheduled_work(vendor_id_fk, scheduled_start);

-- Work logs: list by scheduled work, newest first
CREATE INDEX ix_work_log_schedwork_created_at
ON work_log(scheduled_work_id_fk, created_at DESC);

-- Ticket number should usually be unique per management company
CREATE UNIQUE INDEX ux_ticket_company_ticket_nr
ON ticket(mcompany_id_fk, ticket_nr);

-- Often unit number is unique within a property
CREATE UNIQUE INDEX ux_unit_property_unit_nr
ON unit(property_id_fk, unit_nr);

CREATE INDEX ix_customer_active_by_company
ON customer(mcompany_id_fk)
WHERE is_active = true;

CREATE INDEX ix_resident_active_by_company
ON resident(mcompany_id_fk)
WHERE is_active = true;

CREATE INDEX ix_vendor_active_by_company
ON vendor(mcompany_id_fk)
WHERE is_active = true;


-- Customer: registry_code likely unique (at least per management company)
ALTER TABLE customer ADD CONSTRAINT uq_customer_mcompany_registry UNIQUE (mcompany_id_fk, registry_code);

-- Vendor: registry_code likely unique per management company
ALTER TABLE vendor ADD CONSTRAINT uq_vendor_mcompany_registry UNIQUE (mcompany_id_fk, registry_code);

-- Same appuser cannot be added twice to same management company
ALTER TABLE mcompany_user
  ADD CONSTRAINT uq_mcompany_user_pair UNIQUE (mcompany_id_fk, appuser_id_fk);

-- Same appuser cannot be linked twice to same resident
ALTER TABLE resident_user
  ADD CONSTRAINT uq_resident_user_pair UNIQUE (resident_id_fk, appuser_id_fk);

-- Vendor can have each category only once
ALTER TABLE vendor_ticket_category
  ADD CONSTRAINT uq_vtc_pair UNIQUE (vendor_id_fk, ticket_category_id_fk);

  -- Units: unit number unique within a property
ALTER TABLE unit
  ADD CONSTRAINT uq_unit_property_unitnr UNIQUE (property_id_fk, unit_nr);

-- Ticket number often unique per company (or globally)
ALTER TABLE ticket
  ADD CONSTRAINT uq_ticket_mcompany_ticketnr UNIQUE (mcompany_id_fk, ticket_nr);

-- Contact: prevent duplicates per company/type/value (optional but usually good)
ALTER TABLE contact
  ADD CONSTRAINT uq_contact_mcompany_type_value UNIQUE (mcompany_id_fk, contact_type_id_fk, contact_value);

  -- Only one primary vendor contact per vendor
CREATE UNIQUE INDEX ux_vendor_contact_one_primary
  ON vendor_contact (vendor_id_fk)
  WHERE is_primary = TRUE;

-- Only one primary resident contact per resident
CREATE UNIQUE INDEX ux_resident_contact_one_primary
  ON resident_contact (resident_id_fk)
  WHERE is_primary = TRUE;